name: Build

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: 编译 amlogic-s9xxx-openwrt 固件
        run: |
          echo 开始编译固件
          sudo apt-get update -y
          sudo apt-get full-upgrade -y
          sudo apt-get install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
          echo 编译固件结束
