name: 构建docker镜像并推送到仓库

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: 编译 amlogic-s9xxx-openwrt 固件
        uses: docker/login-action@v1
        with: 
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: 构建并推送至仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: 1.0.0 
