# 工作流程的名称
name: 构建docker镜像并推送到仓库

# 触发条件：当branch触发push（push，merge Pull Request），且 tag 为 image.xxx 时触发工作流。
#on:
#  push:
#    tags: image.*

on:
  workflow_dispatch:

# 工作流程，可包含多个作业
jobs:

  # 作业1名称
  build:
    # 指定的运行器环境
    runs-on: ubuntu-latest
    
    # 作业包含一系列任务，称为 steps
    steps:
      # 检出当前代码（触发工作流时的commits）
      - name: Checkout
        uses: actions/checkout@v2
        
      # setup-qemu 如果您想使用 QEMU 添加仿真支持以便能够针对更多平台进行构建，则 action 会很有用
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      # setup-buildxaction 将默认使用docker-container 构建器驱动程序创建和引导构建器。非必需
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      

      - name: 登录到docker仓库
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 构建并推送，详见：https://docs.github.com/zh/actions/publishing-packages/publishing-docker-images
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: 构建docker镜像并推送
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          #tags: registry.cn-shenzhen.aliyuncs.com/xxxx/image-name:v1
          tags: android_build:v1